In [6]:
#Course : CS 513 - Knowledge discovery and Data mining
#Course Instructor:- Khashayar Dehnad
#First Name: Keval
#Last Name: Sompura
#Id: 20033127
#Assignment: 10 - Similarity
#Description: Implementation of similarity

In [7]:
import pandas as pd
from sklearn.metrics import jaccard_score
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
folder='C:/Users/Asus/OneDrive/Stevens/Sem-2/KDDM/HW10/'
file='Recipe.csv'
data = pd.read_csv(folder+file)
data.head()

,Recipe,Tomato,Garlic,Salt,Onion,TomatoPaste,OliveOil,Celery,Broth,GreenPepper,...,Paprika,Thyme,Tomatillo,JalapenoPepper,WorcestershireSauce,Lime,Eggplant,GreenOlives,Capers,Sugar
0,Spag_Sauce,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Spag_Meat_Sauce,1,1,1,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,Eggplant_Relish,0,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,1,1,1,1
3,Creole_Sauce,1,0,1,1,1,1,1,1,1,...,1,1,0,0,1,0,0,0,0,0
4,Salsa,1,1,1,1,0,0,0,0,0,...,0,0,1,1,0,1,0,0,0,0

In [ ]:
# Calculate Jaccard similarity for each pair of recipes
jaccard_similarities = pd.DataFrame(index=data['Recipe'], columns=data['Recipe'])

for i, recipe1 in enumerate(data['Recipe']):
    for j, recipe2 in enumerate(data['Recipe']):
        if i <= j:
            similarity = jaccard_score(data.iloc[i, 1:].astype(int), data.iloc[j, 1:].astype(int), average='binary')
            jaccard_similarities.loc[recipe1, recipe2] = similarity
            jaccard_similarities.loc[recipe2, recipe1] = similarity

jaccard_similarities

Recipe,Spag_Sauce,Spag_Meat_Sauce,Eggplant_Relish,Creole_Sauce,Salsa,Enchilada_Sauce,new
Recipe,,,,,,,
Spag_Sauce,1.0,0.4,0.416667,0.333333,0.333333,0.066667,0.875
Spag_Meat_Sauce,0.4,1.0,0.294118,0.388889,0.235294,0.05,0.333333
Eggplant_Relish,0.416667,0.294118,1.0,0.235294,0.214286,0.0,0.333333
Creole_Sauce,0.333333,0.388889,0.235294,1.0,0.176471,0.111111,0.266667
Salsa,0.333333,0.235294,0.214286,0.176471,1.0,0.066667,0.363636
Enchilada_Sauce,0.066667,0.05,0.0,0.111111,0.066667,1.0,0.071429
new,0.875,0.333333,0.333333,0.266667,0.363636,0.071429,1.0

In [15]:
# Calculate cosine similarity for each pair of recipes
cosine_similarities = pd.DataFrame(
    cosine_similarity(data.iloc[:, 1:]), 
    index=data['Recipe'], 
    columns=data['Recipe']
)

cosine_similarities

Recipe,Spag_Sauce,Spag_Meat_Sauce,Eggplant_Relish,Creole_Sauce,Salsa,Enchilada_Sauce,new
Recipe,,,,,,,
Spag_Sauce,1.000000,0.588348,0.589256,0.510310,0.500000,0.125000,0.935414
Spag_Meat_Sauce,0.588348,1.000000,0.462250,0.560449,0.392232,0.098058,0.524142
Eggplant_Relish,0.589256,0.462250,1.000000,0.384900,0.353553,0.000000,0.503953
Creole_Sauce,0.510310,0.560449,0.384900,1.000000,0.306186,0.204124,0.436436
Salsa,0.500000,0.392232,0.353553,0.306186,1.000000,0.125000,0.534522
Enchilada_Sauce,0.125000,0.098058,0.000000,0.204124,0.125000,1.000000,0.133631
new,0.935414,0.524142,0.503953,0.436436,0.534522,0.133631,1.000000